// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2582.bet.subsystems;


import org.usfirst.frc2582.bet.Robot;
import org.usfirst.frc2582.bet.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Spark;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import com.ctre.phoenix.motorcontrol.can.VictorSPX;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.sensors.PigeonIMU;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class box extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private TalonSRX roller;                //initialize a TalonSRX
    private VictorSPX roller2;
    private DigitalInput laser;             //initialize a DigitalInput(on and off)

    private PigeonIMU gyro;                 //initialize pigeonIMU(gyro)

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public box() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        roller = new TalonSRX(5);           //roller is declared as TalonSRX ID 5
        roller.configFactoryDefault();      //factory default idk why but every code i see needs it

        roller2 = new VictorSPX(62);
        roller2.configFactoryDefault();

        roller.setInverted(true);
        roller2.setInverted(true);
        roller2.follow(roller);

        gyro = new PigeonIMU(roller);       //gyro is declared as pigeomIMU with roller

        laser = new DigitalInput(0);        //laser is declared as DigitalInput port 0

        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());

    }

    @Override
    public void periodic() 
    {
        // Put code here to be run every loop

    }

    //takes the ball in
    public void suck()
    {
        roller.set(ControlMode.PercentOutput, .5 );       //sets roller to intake at .6 volts in the negative direction
    }

    //spits the ball
    public void spit()
    {
        roller.set(ControlMode.PercentOutput, -.75);         //sets roller to outtake at .75 volts in the possitive direction
    }

    public void stop()
    {
        roller.set(ControlMode.PercentOutput, 0);           //sets the roller to stop at 0 volts
    }

    public boolean IsBallThere()
    {
        boolean a = !laser.get();                           //makes a boolean to get laser status
        Robot.blinkin.box(a);                               //sets blinkin to the boolean
        return a;                                           //returns the state of the laser
    }

    

    public void printLOL()
    {
        double [] ypr = new double[3];                              //creates an array of double size 3
        gyro.getYawPitchRoll(ypr);                                  //sets the array to the values of yaw, pitch, roll
        System.out.println(ypr[0] + " " + ypr[1] + " " + ypr[2]);   //prints it out in the screen
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

